# Generated by Django 5.0.4 on 2024-12-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_compte', models.EmailField(max_length=55, unique=True)),
                ('mdp_compte', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_event', models.DateTimeField()),
                ('date_fin_event', models.DateTimeField()),
                ('titre_event', models.CharField(max_length=32)),
                ('lieu_event', models.CharField(max_length=32)),
                ('description_event', models.CharField(max_length=255)),
                ('disponibilite_event', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prs', models.CharField(max_length=255)),
                ('prenom_prs', models.CharField(max_length=126)),
                ('email_prs', models.EmailField(max_length=32, unique=True)),
                ('role_pers', models.CharField(choices=[('organisateur', 'Organisateur'), ('participant', 'Participant')], max_length=32)),
                ('id_compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_evenement.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Participer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_virtuel', models.CharField(max_length=32)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gestion_evenement.evenement')),
                ('id_prs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='gestion_evenement.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_notif', models.CharField(max_length=255)),
                ('date_notif', models.DateTimeField(auto_now_add=True)),
                ('type_notif', models.CharField(max_length=128)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion_evenement.evenement')),
                ('id_prs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to='gestion_evenement.personne')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='id_prs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_crees', to='gestion_evenement.personne'),
        ),
        migrations.CreateModel(
            name='Discuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_msg', models.TextField()),
                ('date_envoi_msg', models.DateTimeField(auto_now_add=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gestion_evenement.evenement')),
                ('id_prs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='gestion_evenement.personne')),
            ],
        ),
    ]
