# Generated by Django 5.0.4 on 2024-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_evenement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='disponibilite_event',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='notifier',
            name='type_notif',
            field=models.CharField(choices=[('rappel', 'Rappel'), ('mise_a_jour', 'Mise à jour'), ('alerte', 'Alerte')], max_length=32),
        ),
        migrations.AlterField(
            model_name='participer',
            name='ticket_virtuel',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
